[package]
name = "solfunmeme-banner"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "solfunmeme-banner-cli"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
colored = "2.0.0"
figlet-rs = "0.1.5"
clap = { version = "4.0", features = ["derive"] }
